// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./components/Button.vue')['default']
    Contact: typeof import('./components/Contact.vue')['default']
    DesktopNavbar: typeof import('./components/Navbar/DesktopNavbar.vue')['default']
    FeatureItem: typeof import('./components/FeatureItem.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Hero: typeof import('./components/Hero.vue')['default']
    Icon: typeof import('~icons/ic/on')['default']
    MainIntro: typeof import('./components/MainIntro.vue')['default']
    MobileNavbar: typeof import('./components/Navbar/MobileNavbar.vue')['default']
    MobileNavDrawer: typeof import('./components/Navbar/MobileNavDrawer.vue')['default']
    Navbar: typeof import('./components/Navbar/Navbar.vue')['default']
    Navbar2: typeof import('./components/Navbar2.vue')['default']
    README: typeof import('./components/README.md')['default']
    SectionHeader: typeof import('./components/SectionHeader.vue')['default']
    TestimonialItem: typeof import('./components/TestimonialItem.vue')['default']
    Testimonials: typeof import('./components/Testimonials.vue')['default']
    TwoFeatures: typeof import('./components/TwoFeatures.vue')['default']
    WhoWeAre: typeof import('./components/WhoWeAre.vue')['default']
  }
}

export { }
